### ISSUE TITLE
difference between the JSON files and the C++ code?

### ISSUE THREAD

**Issue by longemen3000** [usnistgov/SAFTsuperanc#1]
on the JSON file there are 41 chebishev expansions for each of the saturation densities, but the C++ code seems to be using another set of constants for those.

**Comment by longemen3000** [comment]
also,there are slight differences in the crit expansions. for example, the first coeff in the JSON (https://github.com/usnistgov/SAFTsuperanc/blob/master/output/PCSAFT_crit_pts_expansions.json) is 4.894943841893271, whereas the first coeff in the C++ (https://github.com/usnistgov/SAFTsuperanc/blob/b33768605da484fa6f969a7f2eb28576cf4f9435/implementation/PCSAFTsuperancillary_crit.hpp#L7) is 4.894943841893273 (2 eps)

**Comment by ianhbell** [comment]
Did you run the code to re-generate the headers? They should be in sync (I hope).

**Comment by longemen3000** [comment]
not yet. i'm gonna run those and report back
